devsecopsmaturitymodel/DevSecOps-MaturityModel

Dockerfile
data-yml.php
data.php
data/BuildandDeployment.yml
data/CultureandOrg.yml
navi.php
startDocker.bash
usefulnessHardness.php

- added * (asterisk) where additional context is needed, For example, there are a number of references to availability but not always clear whether this refers to build or deployment.
- translation only at this stage, may provide feedback on structure at a later time
- change container port mapping for local host (80 is often in use)

Initial translation of Build & Deployment

---

data/CultureandOrg.yml

Fixed a typo tragets = targets

Update CultureandOrg.yml (#1)

---

data/BuildandDeployment.yml
data/CultureandOrg.yml
data/Informationgathering.yml
data/Infrastructure.yml
data/TestandVerification.yml

Changed typos, translated text from German to English and cleaned formatting.

Changed data 

---

README.md

Added two links to the readme.md file... guess we need a couple of more, however, now at least we have a starting point for this.

added links to readme.md

---

data/CultureandOrg.yml
data/TestandVerification.yml

Fix newlines

---

README.md

Added link to dsomm.timo-pagel.de

Added link to dsomm.timo-pagel.de

---

data/BuildandDeployment.yml

- small editorial changes (eg. use `>-` in yaml)
- fix typos

Typos and editorial.

---

data/Implementation.yml

Simple, one character typo in Implementation.yml

Typo in Implementation.yml outcoing --> outgoing

---

USAGE.md

- editorial improvements to USAGE.md

editorial: USAGE.md  improvements.

---

.gitignore
data/maturity-levels.yaml
head.php

Moves maturity levels in yaml so that we can add more levels if needed
or better describe them directly without touching the php

Fix: #47. Maturity levels moved to yaml.

---

data.php

Reduce  getElementContent complexity

---

assets/js/scutter.js
data.php
scutter.php

fixes indexerror in scutter.php

Fix indexerror in scutter.php

---

Dockerfile
scripts/merge-dimensions.py

_merge-dimensions.py_ is useable locally without a container.
In addtion, selectedData.csv is by default writeable.
@ioggstream

Usage of Migrations.py locally

---

README.md
USAGE.md

Improve md.

---

.github/workflows/test.yml

Execute phptidy
Requirement from https://github.com/wurstbrot/DevSecOps-MaturityModel/issues/68

add test.yml

---

data-new/BuildAndDeployment/Sub-Dimensions.yaml
data-new/CultureAndOrganization/Design.yaml
data-new/CultureAndOrganization/EducationAndGuidance.yaml
data-new/Implementation/ApplicationHardening.yaml
data-new/Implementation/InfrastructureHardening.yaml
data-new/InformationGathering/Logging.yaml
data-new/InformationGathering/Monitoring.yaml
data-new/TestAndVerification/Consolidation.yaml
data-new/TestAndVerification/DynamicDepthForInfrastructure.yaml
data-new/TestAndVerification/StaticDepthForApplications.yaml
data-new/TestAndVerification/StaticDepthForInfrastructure.yaml

Love the content, noticed some mispellings, so I ran aspell check on the files in data-new. Some of those could be localization differences between en-GB and en-US, so feel free to comment on those if you would prefer they remain the same.

Manually run Aspell Check

---

.gitignore
docker-compose.dev.yml
docker-compose.yml

Fix: #75. Improve dockerfiles.

---

.gitignore
Dockerfile

@ioggstream the changes in https://github.com/wurstbrot/DevSecOps-MaturityModel/pull/77 couldn't be build on my machine due to version problems and no wget.

fix: wget and versions

---

data-new/BuildAndDeployment/Sub-Dimensions.yaml
data-new/CultureAndOrganization/Design.yaml
data-new/CultureAndOrganization/EducationAndGuidance.yaml
data-new/CultureAndOrganization/Process.yaml
data-new/Implementation/InfrastructureHardening.yaml
data-new/InformationGathering/Logging.yaml
data-new/InformationGathering/Monitoring.yaml
data-new/TestAndVerification/ApplicationTests.yaml
data-new/TestAndVerification/Consolidation.yaml
data-new/TestAndVerification/DynamicDepthForApplications.yaml
data-new/TestAndVerification/DynamicDepthForInfrastructure.yaml
data-new/TestAndVerification/StaticDepthForApplications.yaml
data-new/TestAndVerification/StaticDepthForInfrastructure.yaml

Fix: #80. Remove SAMM v1 references from data.

---

data/dimensions-subdimensions-activties/BuildAndDeployment/Sub-Dimensions.yaml
data/dimensions-subdimensions-activties/CultureAndOrganization/Design.yaml
data/dimensions-subdimensions-activties/CultureAndOrganization/EducationAndGuidance.yaml
data/dimensions-subdimensions-activties/CultureAndOrganization/Process.yaml
data/dimensions-subdimensions-activties/Implementation/ApplicationHardening.yaml
data/dimensions-subdimensions-activties/Implementation/InfrastructureHardening.yaml
data/dimensions-subdimensions-activties/InformationGathering/Logging.yaml
data/dimensions-subdimensions-activties/InformationGathering/Monitoring.yaml
data/dimensions-subdimensions-activties/TestAndVerification/ApplicationTests.yaml
data/dimensions-subdimensions-activties/TestAndVerification/Consolidation.yaml
data/dimensions-subdimensions-activties/TestAndVerification/DynamicDepthForApplications.yaml
data/dimensions-subdimensions-activties/TestAndVerification/DynamicDepthForInfrastructure.yaml
data/dimensions-subdimensions-activties/TestAndVerification/StaticDepthForApplications.yaml
data/dimensions-subdimensions-activties/TestAndVerification/StaticDepthForInfrastructure.yaml
data/dimensions-subdimensions-activties/TestAndVerification/Test-Intensity.yaml
data/dimensions-subdimensions-activties/implementations.yaml
data/generateDimensions.php
docker-compose.dev.yml
scripts/test_jsonpath.py
tests.sh

- normalizes implementations using json-pointers ($ref) instead of yaml anchors
- implementation inventory is in `implementation.yaml` https://github.com/wurstbrot/DevSecOps-MaturityModel/pull/86/files#diff-ec9dd08ebd9ae00a5d4f506a1310c3f8cc83e64ff1727c2033fd0c167336f544

Normalize implementations using json-pointers

---

data/dimensions-subdimensions-activities/CultureAndOrganization/Process.yaml
data/dimensions-subdimensions-activities/implementations.yaml

add source code protection developed at the open security summit.

feat: Add source code protection

---

USAGE.md
data/dimensions-subdimensions-activities/BuildAndDeployment/PatchManagement.yaml
data/dimensions-subdimensions-activities/CultureAndOrganization/EducationAndGuidance.yaml
data/dimensions-subdimensions-activities/TestAndVerification/Consolidation.yaml

Adjust levels with Rainer Haffner.

Adjustmetrics levels

---

src/app/app.component.html
src/app/app.module.ts
src/app/component/matrix/matrix.component.css
src/app/component/matrix/matrix.component.html
src/app/component/matrix/matrix.component.ts
src/app/component/top-header/top-header.component.css
src/app/component/top-header/top-header.component.html
src/app/component/top-header/top-header.component.spec.ts
src/app/component/top-header/top-header.component.ts
src/app/material/material.module.ts
src/custom-theme.scss
src/index.html

Changes made:
- Top header implemented
- CSS changes
- Implementation of static matrix table

Changes made on 06/06/21 

---

.github/workflows/ESLint.yml
package-lock.json
package.json
src/app/component/matrix/matrix.component.html
src/app/component/matrix/matrix.component.ts
src/app/service/yaml-parser.service.spec.ts
src/app/service/yaml-parser.service.ts
src/assets/YAML/sample.yaml

Added:
- ESLint github action added
- YML Parse service generated
- Dynamic allocation of 'Level' columns for matrix table.

Changes made on 07/06/21 and 08/06/21

---

src/app/app.component.css
src/app/app.module.ts
src/app/component/logo/logo.component.css
src/app/component/main-content/main-content.component.css
src/app/component/matrix/matrix.component.css
src/app/component/matrix/matrix.component.html
src/app/component/matrix/matrix.component.ts
src/app/component/top-header/top-header.component.css
src/app/material/material.module.ts

Added:
Chips that allow for personalized reconstruction of the table rows based on sub domains.

Added chips that allow for personalized reconstruction of table rows

---

src/app/app-routing.module.ts
src/app/app.component.css
src/app/app.module.ts
src/app/component/logo/logo.component.css
src/app/component/main-content/main-content.component.css
src/app/component/matrix/matrix.component.css
src/app/component/matrix/matrix.component.html
src/app/component/matrix/matrix.component.ts
src/app/component/task-description/task-description.component.css
src/app/component/task-description/task-description.component.html
src/app/component/task-description/task-description.component.spec.ts
src/app/component/task-description/task-description.component.ts
src/app/component/top-header/top-header.component.css
src/app/material/material.module.ts

Added:
- expansion list 
- expand all and collapse all button 
- connected it to the matrix table

Added expansion list

---

src/app/component/matrix/matrix.component.html
src/app/component/matrix/matrix.component.ts

Added:
- Dynamic assignment of level columns

Dynamic assignment of level columns

---

src/assets/YAML/default/BuildAndDeployment/Build.yaml
src/assets/YAML/default/BuildAndDeployment/Deployment.yaml
src/assets/YAML/default/BuildAndDeployment/PatchManagement.yaml
src/assets/YAML/default/CultureAndOrganization/Design.yaml
src/assets/YAML/default/CultureAndOrganization/EducationAndGuidance.yaml
src/assets/YAML/default/CultureAndOrganization/Process.yaml
src/assets/YAML/default/Implementation/ApplicationHardening.yaml
src/assets/YAML/default/Implementation/DevelopmentAndSourceControl.yaml
src/assets/YAML/default/Implementation/InfrastructureHardening.yaml
src/assets/YAML/default/Implementation/VersionControl.yaml
src/assets/YAML/default/InformationGathering/Logging.yaml
src/assets/YAML/default/InformationGathering/Monitoring.yaml
src/assets/YAML/default/TestAndVerification/ApplicationTests.yaml
src/assets/YAML/default/TestAndVerification/Consolidation.yaml
src/assets/YAML/default/TestAndVerification/DynamicDepthForApplications.yaml
src/assets/YAML/default/TestAndVerification/DynamicDepthForInfrastructure.yaml
src/assets/YAML/default/TestAndVerification/StaticDepthForApplications.yaml
src/assets/YAML/default/TestAndVerification/StaticDepthForInfrastructure.yaml
src/assets/YAML/default/TestAndVerification/Test-Intensity.yaml

Added:
- new YAML files with updated schema

Added new YAML files

---

src/app/component/circular-heatmap/circular-heatmap.component.css
src/app/component/circular-heatmap/circular-heatmap.component.html
src/app/component/circular-heatmap/circular-heatmap.component.ts
src/app/material/material.module.ts

Added:
- material card for heatmap view 
- made all variables TS
- Minor bug fixes
- Added Checkboxes

Added material card for heatmap view + made all variables TS

---

src/app/component/circular-heatmap/circular-heatmap.component.css
src/app/component/circular-heatmap/circular-heatmap.component.html
src/app/component/circular-heatmap/circular-heatmap.component.ts

Added:
- Automatic color changes 
- hot reload of heatmap

Added Automatic color changes and hot reload of heatmap

---

src/app/app-routing.module.ts
src/app/component/task-description/task-description.component.html
src/app/component/task-description/task-description.component.ts
src/assets/YAML/generated/sample.yaml

Added:
- More YAML Parsing in Task Description section

More YAML Parsing in Task Description section

---

src/app/component/circular-heatmap/circular-heatmap.component.ts
src/assets/YAML/generated/sample.yaml

Added:
- 'isImplemented' in YAML 
- import of YAML data to make circular heatmap dynamic

Added 'isImplemented' in YAML and made circular heatmap dynamic

---

src/app/app.module.ts
src/app/component/circular-heatmap/circular-heatmap.component.ts
src/app/component/matrix/matrix.component.css
src/app/component/matrix/matrix.component.html
src/app/component/task-description/task-description.component.html
src/app/component/tree-map/tree-map.component.css
src/app/component/tree-map/tree-map.component.html
src/app/component/tree-map/tree-map.component.spec.ts
src/app/component/tree-map/tree-map.component.ts

Added:
Expansion of fields in implementation by clicking on it 
Dependency tree

Angular UI

---

src/app/component/matrix/matrix.component.html
src/assets/YAML/generated/generated.yaml

Changed implemented tasks text color to green

Task colored green in matrix section

---

src/app/component/matrix/matrix.component.css
src/app/component/matrix/matrix.component.html
src/app/component/readme-to-html/readme-to-html.component.ts
src/app/component/usage/usage.component.html
src/assets/Markdown Files/README.md

Cleaned code and fixed sponsor image

Cleaned code

---

src/assets/YAML/default/implementations.yaml

Add URLs based on websites and Mitre D3FEND. See #162

---

src/assets/YAML/default/TestAndVerification/ApplicationTests.yaml

As mentioned by @ioggstream in https://github.com/wurstbrot/DevSecOps-MaturityModel/issues/161

Removal of httpunit

---

src/assets/YAML/default/Implementation/DevelopmentAndSourceControl.yaml
src/assets/YAML/default/TestAndVerification/StaticDepthForApplications.yaml
src/assets/YAML/generated/generated.yaml

Fix: #165. Typo in SAMM V-ST-A.

---

src/assets/YAML/default/BuildAndDeployment/Build.yaml
src/assets/YAML/default/BuildAndDeployment/Deployment.yaml
src/assets/YAML/default/Implementation/DevelopmentAndSourceControl.yaml
src/assets/YAML/default/TestAndVerification/DynamicDepthForApplications.yaml
src/assets/YAML/default/TestAndVerification/StaticDepthForApplications.yaml
src/assets/YAML/default/implementations.yaml
src/assets/YAML/generated/generated.yaml

- some editorial suggestions
- add Multi-Factor authentication to SCM
- add WEB API Design validation and associated tools

Editorial suggestions.

---

src/app/component/matrix/matrix.component.spec.ts
src/app/component/matrix/matrix.component.ts
src/app/component/sidenav-buttons/sidenav-buttons.component.spec.ts

Unit Test for:
- Matrix Component
- Side Navigation Bar Component

More Tests

---

src/assets/YAML/default/BuildAndDeployment/Deployment.yaml
src/assets/YAML/default/Implementation/DevelopmentAndSourceControl.yaml
src/assets/YAML/default/TestAndVerification/DynamicDepthForApplications.yaml
src/assets/YAML/default/implementations.yaml
src/assets/YAML/generated/generated.yaml

More implementations. See #162.

---

src/app/component/top-header/top-header.component.spec.ts

Added tests for:
- header creation
- header update

Added more tests

---

src/app/component/task-description/task-description.component.spec.ts

- Checking if assessment is being generated on activity description
- Checking if comments is being generated on activity description
- Checking if references is being generated on activity description

Added more tests to activity description

---

src/app/app.component.spec.ts
src/app/component/mapping/mapping.component.spec.ts
src/app/component/matrix/matrix.component.spec.ts

Added:
- Test to check if chips in matrix section can be deleted
- Test to check if chips in mapping section can be deleted
- Test to check for table generation in mapping section

Implemented more tests

---

.github/workflows/main.yml

Multi-arch builds work. I couldn't test registry upload.

Multi arch builds

---

src/app/component/circular-heatmap/circular-heatmap.component.ts

fix heatmap down 

---

README.md

I had to use this command instead to run and display locally.

Update Instructions to use generated.yaml in README.md

---

src/assets/YAML/default/BuildAndDeployment/Deployment.yaml
src/assets/YAML/default/BuildAndDeployment/PatchManagement.yaml
src/assets/YAML/default/implementations.yaml

I have made several additions:

Defined Decomissioning Process description & Kubernetes Admission URL

---

src/assets/YAML/default/CultureAndOrganization/EducationAndGuidance.yaml

Recommended by @bob5ec in https://github.com/wurstbrot/DevSecOps-MaturityModel/pull/215

enhance coaching

---

src/assets/YAML/default/implementations.yaml

I believe the Indentation for the last few implementations was wrong. 
Now they get displayed in the ui.

fixed indentation of implementations

---

src/app/component/circular-heatmap/circular-heatmap.component.css
src/app/component/circular-heatmap/circular-heatmap.component.html
src/app/component/circular-heatmap/circular-heatmap.component.ts

This PR is dealing with issue #192 
Will be creating an overlay which would look something like this:

Overlay for Comprehensive Heatmap

---

Development.md
src/assets/YAML/default/BuildAndDeployment/Build.yaml
src/assets/YAML/default/BuildAndDeployment/Deployment.yaml
src/assets/YAML/default/BuildAndDeployment/PatchManagement.yaml
src/assets/YAML/default/CultureAndOrganization/Design.yaml
src/assets/YAML/default/CultureAndOrganization/EducationAndGuidance.yaml
src/assets/YAML/default/CultureAndOrganization/Process.yaml
src/assets/YAML/default/Implementation/ApplicationHardening.yaml
src/assets/YAML/default/Implementation/DevelopmentAndSourceControl.yaml
src/assets/YAML/default/Implementation/InfrastructureHardening.yaml
src/assets/YAML/default/InformationGathering/Logging.yaml
src/assets/YAML/default/InformationGathering/Monitoring.yaml
src/assets/YAML/default/TestAndVerification/ApplicationTests.yaml
src/assets/YAML/default/TestAndVerification/Consolidation.yaml
src/assets/YAML/default/TestAndVerification/DynamicDepthForApplications.yaml
src/assets/YAML/default/TestAndVerification/DynamicDepthForInfrastructure.yaml
src/assets/YAML/default/TestAndVerification/StaticDepthForApplications.yaml
src/assets/YAML/default/TestAndVerification/StaticDepthForInfrastructure.yaml
src/assets/YAML/default/TestAndVerification/Test-Intensity.yaml
src/assets/YAML/default/implementations.yaml
src/assets/YAML/schemas/dsomm-implementations-schema.json
src/assets/YAML/schemas/dsomm-schema-build-and-deployment.json
src/assets/YAML/schemas/dsomm-schema-culture-and-organization.json
src/assets/YAML/schemas/dsomm-schema-implementation.json
src/assets/YAML/schemas/dsomm-schema-information-gathering.json
src/assets/YAML/schemas/dsomm-schema-test-and-verification.json

Hello @wurstbrot 
What do you think about this approach?
Thanks to the definition of the schema, certain schematic errors can be recognised directly (if you have yaml validation in the IDE).
If I have time soon, I can look into some of these errors.

Added schemas for validation of DSOMM yamls

---

src/assets/YAML/default/BuildAndDeployment/Build.yaml
src/assets/YAML/default/BuildAndDeployment/Deployment.yaml
src/assets/YAML/default/CultureAndOrganization/EducationAndGuidance.yaml
src/assets/YAML/default/Implementation/ApplicationHardening.yaml
src/assets/YAML/default/Implementation/DevelopmentAndSourceControl.yaml
src/assets/YAML/default/Implementation/InfrastructureHardening.yaml
src/assets/YAML/default/InformationGathering/Monitoring.yaml
src/assets/YAML/default/TestAndVerification/Consolidation.yaml
src/assets/YAML/default/TestAndVerification/DynamicDepthForInfrastructure.yaml
src/assets/YAML/default/TestAndVerification/StaticDepthForInfrastructure.yaml
src/assets/YAML/default/implementations.yaml

Fix spelling errors.

---

src/assets/YAML/default/BuildAndDeployment/Build.yaml
src/assets/YAML/default/BuildAndDeployment/Deployment.yaml
src/assets/YAML/default/BuildAndDeployment/PatchManagement.yaml
src/assets/YAML/default/CultureAndOrganization/Design.yaml
src/assets/YAML/default/CultureAndOrganization/EducationAndGuidance.yaml
src/assets/YAML/default/CultureAndOrganization/Process.yaml
src/assets/YAML/default/Implementation/ApplicationHardening.yaml
src/assets/YAML/default/Implementation/DevelopmentAndSourceControl.yaml
src/assets/YAML/default/Implementation/InfrastructureHardening.yaml
src/assets/YAML/default/InformationGathering/Logging.yaml
src/assets/YAML/default/InformationGathering/Monitoring.yaml
src/assets/YAML/default/TestAndVerification/ApplicationTests.yaml
src/assets/YAML/default/TestAndVerification/Consolidation.yaml
src/assets/YAML/default/TestAndVerification/DynamicDepthForApplications.yaml
src/assets/YAML/default/TestAndVerification/DynamicDepthForInfrastructure.yaml
src/assets/YAML/default/TestAndVerification/StaticDepthForApplications.yaml
src/assets/YAML/default/TestAndVerification/StaticDepthForInfrastructure.yaml
src/assets/YAML/default/TestAndVerification/Test-Intensity.yaml
src/assets/YAML/default/implementations.yaml
src/assets/YAML/schemas/dsomm-implementations-schema.json
src/assets/YAML/schemas/dsomm-schema-build-and-deployment.json
src/assets/YAML/schemas/dsomm-schema-culture-and-organization.json
src/assets/YAML/schemas/dsomm-schema-implementation.json
src/assets/YAML/schemas/dsomm-schema-information-gathering.json
src/assets/YAML/schemas/dsomm-schema-test-and-verification.json

Hello
I added the uuid into the json schema like suggested in #242.
However now the uuid is still missing for all activities at the moment. One would therefore have to initially generate and enter a UUID for each activity in order to be compliant with the schema. 
If I have time sometime soon, I could take a look at it, but someone else can also do it.
Kind regards

add uuid to json schema

---

src/app/component/task-description/task-description.component.html
src/app/component/task-description/task-description.component.spec.ts
src/app/component/task-description/task-description.component.ts

Display UUID in task description. 
(UUID's added in https://github.com/wurstbrot/DevSecOps-MaturityModel/pull/243)

Display uuid on task description

---

src/app/component/activity-description/activity-description.component.html
src/app/component/activity-description/activity-description.component.spec.ts

enhancement: Task-description tests reference elements by ID

---

package-lock.json
src/app/component/mapping/mapping.component.html
src/app/component/mapping/mapping.component.ts

**Additions:**
- Adds all teams and their implementation status to the downloadable excel file.

BUG: Add teams and their implementations to excel

---

.prettierignore
src/app/component/activity-description/activity-description.component.html
src/app/component/activity-description/activity-description.component.spec.ts
src/app/component/activity-description/activity-description.component.ts

Fixes #314
Changes:
- Added TeamsEvidence
- Removed Evidence
Screenshot for change:
Changes in generated.yml:
```
teamsEvidence:
Default: this is my evidence in markdown
A: this is my second evidence in markdown
```

Added teamsEvidence

---

src/assets/Markdown Files/userday.md

Also optimized the images a bit.
These were / still are huge and load very very slowly on slower networks.

Add DSOMM / Juice Shop Userday Session Descriptions for MultiJuicer

---

src/app/component/mapping/mapping.component.html
src/app/component/mapping/mapping.component.ts

Features:
- removed evidence column from excel 
- Added teams evidence columns in excel
Closes #322

added teamsEvidence to excel

---

src/app/component/mapping/mapping.component.html
src/app/component/mapping/mapping.component.ts

added activity level in excel

---

src/app/component/activity-description/activity-description.component.ts
src/app/component/circular-heatmap/circular-heatmap.component.ts

Fixed bug where changes done in circular heatmap were not shown in activity description 

---

src/app/component/circular-heatmap/circular-heatmap.component.ts

Ref: https://github.com/devsecopsmaturitymodel/DevSecOps-MaturityModel/issues/324 Page layout still needs fixing. But this fixes the SVG.

#324 Scalable SVG

---

src/app/component/circular-heatmap/circular-heatmap.component.ts

Fixes #351 by adding a guard for empty localStorage. 
Bug was introduced in #349.

Add guard for empty localStorage

---

.github/workflows/tests.yml

Changes:
- Fixes the installation error in tests.

Bugfix: ignore peer dependencies while installing node packages during test 

---

.releaserc.json

@vbakke some issues exists due to renaming ;)

Change default branch from 'master' to 'main'
