devsecopsmaturitymodel/DevSecOps-MaturityModel

USAGE.md
- Introduces NIST "risk" and "risk function" definitions
- risk is a measure
- references to NIST, FISMA
This is editorial only, no code involved
=> Fix: #50. Define risks and threats.

bib.php, data.php, detail.php, functions.php, graph.php, head.php, index.php, mappings.php, md.php, navi.php, newFolder-Migration-2021.php, report-samm.php, report.php, scutter.php, spiderweb.php, spiderwebData.php, test-yaml.php, usefulnessHardness.php
reformats code with phptidy
```
wget https://github.com/cmrcx/phptidy/blob/master/phptidy.php
php phptidy.php replace *.php
sed -i 's,\t,  ,g' *.php
```
=> Reformat with phptidy.

data-new/BuildAndDeployment/Sub-Dimensions.yaml, data-new/CultureAndOrganization/Design.yaml, data-new/CultureAndOrganization/EducationAndGuidance.yaml, data-new/CultureAndOrganization/Process.yaml, data-new/CultureAndOrganization/_meta.yaml, data-new/Implementation/ApplicationHardening.yaml, data-new/Implementation/InfrastructureHardening.yaml, data-new/InformationGathering/Logging.yaml, data-new/InformationGathering/Monitoring.yaml, data-new/InformationGathering/_meta.yaml, data-new/TestAndVerification/ApplicationTests.yaml, data-new/TestAndVerification/Consolidation.yaml, data-new/TestAndVerification/DynamicDepthForApplications.yaml, data-new/TestAndVerification/DynamicDepthForInfrastructure.yaml, data-new/TestAndVerification/StaticDepthForApplications.yaml, data-new/TestAndVerification/StaticDepthForInfrastructure.yaml, data-new/TestAndVerification/Test-Intensity.yaml, data-new/TestAndVerification/_meta.yaml, scripts/update_schema.py
- enforces `risk` and `implementation` as lists
- using the provided python script
- the script is provided as a tool for validating the refactor
but it can be removed if you think.
The PHP application should already support `risk` and `implementation` as lists
=> Fix: #76. Reformat yaml files using update_schema.py

data-new/TestAndVerification/StaticDepthForInfrastructure.yaml
Small quick amendment.  It would be great, if there are other English proficient maintainers to double check,
=> Typo/Grammar fix StaticDepthForInfrastructure doc

data/dimensions-subdimensions-activties/BuildAndDeployment/Sub-Dimensions.yaml, data/dimensions-subdimensions-activties/CultureAndOrganization/Design.yaml, data/dimensions-subdimensions-activties/CultureAndOrganization/EducationAndGuidance.yaml, data/dimensions-subdimensions-activties/Implementation/ApplicationHardening.yaml, data/dimensions-subdimensions-activties/Implementation/InfrastructureHardening.yaml, data/dimensions-subdimensions-activties/InformationGathering/Logging.yaml, data/dimensions-subdimensions-activties/InformationGathering/Monitoring.yaml, data/dimensions-subdimensions-activties/TestAndVerification/ApplicationTests.yaml, data/dimensions-subdimensions-activties/TestAndVerification/Consolidation.yaml, data/dimensions-subdimensions-activties/TestAndVerification/DynamicDepthForApplications.yaml, data/dimensions-subdimensions-activties/TestAndVerification/DynamicDepthForInfrastructure.yaml, data/dimensions-subdimensions-activties/TestAndVerification/StaticDepthForApplications.yaml, data/dimensions-subdimensions-activties/TestAndVerification/StaticDepthForInfrastructure.yaml, data/dimensions-subdimensions-activties/TestAndVerification/Test-Intensity.yaml
- renames SAMM activities based on the Activities existing in https://github.com/OWASP/samm/blob/master/Supporting%20Resources/v2.0/Datamodel/Datafiles/ 
It is thus possible to retrieve all activity description using `curl https://raw.githubusercontent.com/OWASP/samm/master/Supporting%20Resources/v2.0/Datamodel/Datafiles/Activity%20${LABEL}.yml`
The resulting information can be displayed on a webapp directly by the browser without being embedded in dsomm.
=> Fix: #73. Use reference from SAMM repo.

data/dimensions-subdimensions-activities/TestAndVerification/DynamicDepthForInfrastructure.yaml
A Fatal error is throwed in `details.php` because dependsOn is filled as a string instead of an array
```
Fatal error: Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in /var/www/html/detail.php:81 Stack trace: #0 /var/www/html/detail.php(81): implode(', ', 'Segmented netwo...') #1 /var/www/html/report.php(68): printDetail('Test and Verifi...', 'Dynamic depth f...', 'Test network se...', Array, true) #2 {main} thrown in /var/www/html/detail.php on line 81
```
To fix it I just updated the involved yaml file
=> Fix dependsOn mistyped

src/app/component/task-description/task-description.component.html, src/app/component/task-description/task-description.component.ts, src/assets/YAML/generated/sample.yaml
Added:
- Compete YAML parsing for task description
=> Completed YAML parsing for task description section

README.md, src/assets/Markdown Files/README.md
Formatting fix in the readme, and command fix on the usage page
=> Typo Fixes for docker run commands

src/app/component/task-description/task-description.component.html, src/app/component/task-description/task-description.component.spec.ts, src/app/component/task-description/task-description.component.ts
- Changed references test to make test more dynamic
=> Minor test fixes

src/app/component/task-description/task-description.component.ts
Reducing the number of clicks on a web page is considered good usability.
Currently a user will always need to click "Expand all" every time they visit the Task Description page, to learn about a new task. For example, reading information about each tasks under "Build and Deployment / Deployment" today would require 22 clicks (plus 10 clicks on the browser Back button). This patch reduces the number of page clicks down to 11.
=> Set Task Description page to start with its information visible

Dockerfile, nginx/default.conf, nginx/location.conf
Enable build and executing on Apple Silicon by added required build deps to the `node-alpine` image and switching out the nginx image to the official one with modifications to Dockerfile to allow rootless operation of nginx.
=> Applesilicon

src/app/component/activity-description/activity-description.component.ts, src/app/component/matrix/matrix.component.html, src/app/component/matrix/matrix.component.ts
BREAKING CHANGE: Use UUID for navigation. Old dimension/subdimesion/activityName will not work anymore
I have let old dimension name/activity etc. stay for SEO.
=> feat:  Use UUID for navigation

src/app/component/circular-heatmap/circular-heatmap.component.ts
=> fix: Properly color empty activities with ligth grey on the circular heatmap component

README.md
This PR fixes the instructions to use custom .yaml files (in particular generated.yaml and meta.yaml) when running the docker image for the DSOMM. 
The problem was that the path to the .yaml files in the docker image were incorrect with respect to the latest docker image. Therefore, I replaced the instances of `/usr/share/nginx/html` by `/srv` in README.md.
=> Fix docker instructions for custom .yaml files in README.md

src/app/component/circular-heatmap/circular-heatmap.component.ts, src/app/component/mapping/mapping.component.html, src/app/component/mapping/mapping.component.ts
The default `generated.yaml` does not incluide `teamsImplemented` for all activites (Software Composition Analysis).
Nor does it have `iso27001-2017` defined for all. 
Nevertheless, DSOMM should not fail id items are missing from the YAML. 
This pull requests fixes #337.
=> Fix failing mapping load

src/app/component/circular-heatmap/circular-heatmap.component.ts
This PR fixes the #338 where unpredictable load order may corrupt the circular heatmap
=> Fix #338 by ensuring correct load order of yaml files

src/app/component/circular-heatmap/circular-heatmap.component.html, src/app/component/circular-heatmap/circular-heatmap.component.ts
=> feature: added markdown rendering to activity desc in circular heatmap

.prettierrc.json, src/app/component/circular-heatmap/circular-heatmap.component.css, src/app/component/circular-heatmap/circular-heatmap.component.html, src/app/component/circular-heatmap/circular-heatmap.component.ts
Fixes #345 
* Space in team names, and team groups now work
* Removed unnecessary loop in toggleTeamGroupSelection()
* Fixed: Filter chips are now initialized after teams have been loaded (no longer just a 100ms delay)
* Fixed: Incorrect background color on hover over 
* Fixed: Team filter initializes with `selected` color (in sync with the 'All' group)
=> Fix #345 Spaces in groupnames

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/component/activity-description/activity-description.component.ts, src/app/component/circular-heatmap/circular-heatmap.component.html, src/app/component/circular-heatmap/circular-heatmap.component.ts, src/app/component/dependency-graph/dependency-graph.component.ts, src/app/component/matrix/matrix.component.html, src/app/component/teams/teams.component.html, src/app/component/teams/teams.component.spec.ts, src/app/component/teams/teams.component.ts
Fixes #344. 
But the discussion in #344 is not quite complete, regarding how to find latest team status.
DSOMM should really centralize the load process of yaml and localstorage in a separate service.  But I'll leave that for later, @wurstbrot.
=> Allow team names to be controlled by meta.yaml

src/app/component/circular-heatmap/circular-heatmap.component.html, src/app/component/circular-heatmap/circular-heatmap.component.ts
In Circular Heatmap, opening the modal dialog displaying the Activity Details, will affect `this.YamlObject`, and thus affect the export of `generated.yaml`, with an extra `navigationExtras` for all activities that have been opened. 
The fix was to assign a shallow copy of the activity, before adding the `navigationExtras`.
=> Remove sideeffect when opening modal dialog

Development.md
Added instruction to setup the development environment
=> Development.md: Add Angualr install instruction

src/app/app.module.ts, src/app/component/circular-heatmap/circular-heatmap.component.html, src/app/component/circular-heatmap/circular-heatmap.component.spec.ts, src/app/component/circular-heatmap/circular-heatmap.component.ts, src/app/component/modal-message/modal-message.component.css, src/app/component/modal-message/modal-message.component.html, src/app/component/modal-message/modal-message.component.spec.ts, src/app/component/modal-message/modal-message.component.ts
Fixes #334, by warning the user before any localStorage is deleted
=> Add warning before deleting browser progress

.github/workflows/main.yml
The current `main.yaml` causes a daily build error in downstream forks (such as [vbakke/DevSecOps-MaturityModel](https://github.com/vbakke/DevSecOps-MaturityModel)).
Don't know if disabling the whole build step all together is the right solution, @wurstbrot. So, I'm happy for input  : )
* Log in to Docker Hub
* Run docker/login-action@v2
* with:
* username: wurstbrot
* ecr: auto
* logout: true
* Error: Username and password required
=> Fix mail.yaml error in downstream forks

README.md, src/app/app.component.html, src/assets/Markdown Files/README.md
Noticed some minor errors for the meta.yaml links inside of DSOMM.
They were previously lining to a non exisisting file, e..g the meta.yaml links here: https://dsomm.owasp.org/usage/
=> Minor link fixes
